image: node:latest

pages:
  script:
    - mkdir .public
    - cp -r portfolio/public_html/* .public/
  artifacts:
    paths:
      - public
  only:
    - main  # Change this to your default branch if different
