image: alpine:latest  # Using a lightweight image

pages:
  script:
    - mkdir public  # Create the public directory
    - cp -r public_html/* public/  # Correctly reference the path
  artifacts:
    paths:
      - public
  only:
    - main  # Change this to your default branch if different
